---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: final
  region: ap-northeast-1
  version: "1.25"
availabilityZones:
- ap-northeast-1a
- ap-northeast-1c
managedNodeGroups:
- name: managed-nodes
  labels:
    role: managed-nodes
  instanceType: t3a.small   # 2 vCPU, 2Gi Memory, 0.0245 USD/hour
  minSize: 1
  maxSize: 7
  desiredCapacity: 2
  # volumeSize: 20
