apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: final-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: final-deployment
  minReplicas: 1
  maxReplicas: 30
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 250Mi
